version: "3"
services:

  client:
    container_name: client
    build: ./packages/client
    expose:
      - ${APP_CLIENT_PORT}
    environment:
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./packages/client/src:/home/app/src
    links:
      - server
    command: bash -c "yarn start"

  server:
    container_name: server
    build: ./packages/server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      - API_HOST=${API_HOST}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - DATABASE_HOST=mongodb://mongo:${DATABASE_PORT}/server
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    depends_on:
      - mongo
    volumes:
      - ./packages/server/src:/home/app/src
    command: yarn start

  mongo:
    container_name: mongoDB
    image: mongo:4.0.10-xenial
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo:/data/db

volumes:
  mongo:
